apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      name: webservice
      labels:
        app: webservice
        env: canary
    spec:
      containers:
        - image: DOCKER_IMAGE
          imagePullPolicy: Always
          name: webservice
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          livenessProbe:
            httpGet:
              port: 8080
              path: /live
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              port: 8080
              path: /ready
            initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: webservice-lb
spec:
  sessionAffinity: ClientIP
  selector:
    app: webservice
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: webservice-np
spec:
  selector:
    app: webservice
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 31080
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 31433
  type: NodePort
#---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: tls-secret
#type: Opaque
#data:
#  key: KEY
#  cert: CERT
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webservice-ingress
spec:
#  tls:
#    - hosts:
#        - webservice-np-edu.openexchange.io
#      secretName: tls-secret
  rules:
    - host: webservice-np-edu.openexchange.io
      http:
        paths:
          - path: /
            backend:
              serviceName: webservice-np
              servicePort: 80