project_name: ${GITHUB_PROJECT}

release:
  github:
    owner: ${GITHUB_USER}
    name: '{{.ProjectName}}'

before:
  hooks:
    - git diff --exit-code

build:
  env:
    - CGO_ENABLED=0
  main: cmd/manager/main.go
  binary: '{{.ProjectName}}'
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
archive:
  format: tar.gz

dockers:
  -
    binaries:
      - '{{.ProjectName}}'
    goos: linux
    goarch: amd64
    image_templates:
      - "{{.Env.DOCKER_USER}}/{{.ProjectName}}:latest"
      - "{{.Env.DOCKER_USER}}/{{.ProjectName}}:{{ .Tag }}"