project_name: openexchange-webservice-go

before:
  hooks:
    - git diff --exit-code

build:
  main: cmd/manager/main.go
  binary: openexchange-webservice-go
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
archive:
  format: tar.gz

dockers:
  - image_templates:
      - "{{.Env.DOCKER_USER}}/{{.ProjectName}}:latest"
      - "{{.Env.DOCKER_USER}}/{{.ProjectName}}:{{ .Tag }}"
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
    - {{.ProjectName}}
    dockerfile: Dockerfile