project_name: openexchange-webservice-go
build:
  main: cmd/manager/main.go
  binary: openexchange-webservice-go
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
archive:
  format: tar.gz