project_name: openexchange-webservice-go

before:
  hooks:
   # - GO111MODULE=off go mod download
    - git diff --exit-code

build:
  main: cmd/manager/main.go
  binary: openexchange-webservice-go
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
archive:
  format: tar.gz

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - mybinary
    # Templates of the Docker image names.
    image_templates:
      - "{{.Env.DOCKER_USER}}/{{.ProjectName}}:latest"
      - "{{.Env.DOCKER_USER}}/{{.ProjectName}}:{{ .Tag }}"
    dockerfile: Dockerfile