sudo: false

language: go

env:
  - GO111MODULE=on

gobuild_args: "-v"
go:
  - 1.12.x

git:
  depth: 1

notifications:
  email:
    - andrey.kandzuba@gmail.com

before_script:
  - go get -u=patch

script:
  - go test -coverprofile=${TRAVIS_BUILD_DIR}/coverage.out -covermode=atomic -coverpkg=all ./...

after_success:
  - export LAST_GIT_TAG_VERSION=$(git describe --abbrev=0 --tags) && export LAST_GIT_TAG_VERSION=${LAST_GIT_TAG_VERSION:1}
  - export GIT_TAG_VERSION=$((LAST_GIT_TAG_VERSION+1))


before_deploy:
  - echo "before_deploy"
  - echo TRAVIS_BRANCH=${TRAVIS_BRANCH}
  - echo TRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
  - echo GIT_TAG_VERSION=${GIT_TAG_VERSION}
deploy:
    provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file: "FILE TO UPLOAD"
    skip_cleanup: true
    on:
      tags: true

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master