sudo: false
env:
  global:
    - GO111MODULE=on
    - REPO_NAME=${TRAVIS_REPO_SLUG}
    - TAG_NAME=${TRAVIS_TAG}
    - BUILD_DIR=${TRAVIS_BUILD_DIR}
    - DOCKER_REGISTRY=docker.io
    - DOCKER_IMAGE="${REPO_NAME}:${TAG_NAME}"
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
    - "$HOME/google-cloud-sdk"
notifications:
  email:
    - ${NOTIFY_EMAIL}
language: go
gobuild_args: "-v"
go:
  - 1.12.x
before_install:
  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then rm -rf $HOME/google-cloud-sdk; rm -rf $HOME/.config/gcloud; curl
    https://sdk.cloud.google.com | bash > /dev/null; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud version
install:
  - GO111MODULE=off go get golang.org/x/tools/cmd/cover
  - GO111MODULE=off go get github.com/mattn/goveralls
script:
  - go test -coverprofile=${BUILD_DIR}/coverage.out -covermode=atomic ./...
  - ${HOME}/gopath/bin/goveralls -coverprofile=${BUILD_DIR}/coverage.out -service=travis-ci
deploy:
  - provider: script
    skip_cleanup: true
    script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
  - provider: script
    skip_cleanup: true
    script: ${BUILD_DIR}/release.sh
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
  - provider: script
    skip_cleanup: true
    script: ${BUILD_DIR}/activate.sh
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
  - provider: script
    skip_cleanup: true
    script: ${BUILD_DIR}/deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"