sudo: false

language: go

env:
  - GO111MODULE=on

gobuild_args: "-v"
go:
  - 1.12.x

git:
  depth: 1

notifications:
  email:
    - andrey.kandzuba@gmail.com

install:
  - GOMODULE=off go get golang.org/x/tools/cmd/cover
  - GOMODULE=off go get github.com/mattn/goveralls
#  - GOMODULE=off go get -u

script:
  - go test -coverprofile=${TRAVIS_BUILD_DIR}/coverage.out -covermode=atomic ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken ${COVERALLS_REPO_TOKEN}

after_success:
#  - test -n "$TRAVIS_TAG" && docker login -u=myuser -p="$DOCKER_PASSWORD"
  - curl -sL https://git.io/goreleaser | bash /dev/stdin --snapshot

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux