steps:
#  - name: 'ubuntu'
#    args: ['bash', '-c', 'echo -coverprofile=coverage.out -service=travis-ci -covermode=atomic -repotoken $$COVERALLS_REPO_TOKEN']
#    secretEnv: ['COVERALLS_REPO_TOKEN']
  - name: 'gcr.io/cloud-builders/go'
    env:
      - GO111MODULE=off
    args: ['get', 'golang.org/x/tools/cmd/cover']
  - name: 'gcr.io/cloud-builders/go'
    env:
      - GO111MODULE=off
    args: ['get', 'github.com/mattn/goveralls']
  - name: 'gcr.io/cloud-builders/go'
    args: ['test', '-coverprofile=coverage.out', '-covermode=atomic', './...']
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: '/go/bin/goveralls'
    args: ['-coverprofile=coverage.out', '-service=travis-ci', '-covermode=atomic', '-repotoken=$$COVERALLS_REPO_TOKEN']
    secretEnv: ['COVERALLS_REPO_TOKEN']
secrets:
  - kmsKeyName: projects/gi-gae/locations/global/keyRings/openexchange-webservice-go/cryptoKeys/coveralls_token
    secretEnv:
      COVERALLS_REPO_TOKEN: |
        CiQAnCXeaYjhNLCBn7V3WAIEFwLq9BSvMcsN9Ld2V+sKykzGEL4SSgBQL80OofuuIdnEBoeDezpp
        PbA8B4JisQGLtbRtuKjKVZaca6xNJny172kKh2AexflO7Ao6ybLhQOHG+EgElrRqqkQ25KPCDVbH
options:
  env:
    - GOPATH=/go
    - GO111MODULE=on
  volumes:
    - name: go-modules
      path: /go