steps:
  - name: 'gcr.io/cloud-builders/go'
    env:
      - GO111MODULE=off
    args: ['get', 'golang.org/x/tools/cmd/cover']
  - name: 'gcr.io/cloud-builders/go'
    env:
      - GO111MODULE=off
    args: ['get', 'github.com/mattn/goveralls']
  - name: 'gcr.io/cloud-builders/go'
    args: ['test', '-coverprofile=coverage.out', '-covermode=atomic', './...']
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: '/go/bin/goveralls'
    args: ['-coverprofile=coverage.out', '-service=travis-ci', '-covermode=atomic', '-repotoken', '${_COVERALLS_REPO_TOKEN}']
options:
  env:
    - GOPATH=/go
    - GO111MODULE=on
#    - REPO_SLUG='$(echo $REPO_NAME | sed -e "s|_|/|g" | sed -e "s|github/||g")'
#    - GITHUB_NAME='$(echo $REPO_SLUG | sed -e "s|/| |g" | awk \{'print $1'\})'
#    - GITHUB_PROJECT='$(echo $REPO_SLUG | sed -e "s|/| |g" | awk \{'print $2'\})'
  volumes:
    - name: go-modules
      path: /go