steps:
  - name: 'gcr.io/cloud-builders/go'
    env:
      - GO111MODULE=off
    args: ['get', 'golang.org/x/tools/cmd/cover']
  - name: 'gcr.io/cloud-builders/go'
    env:
      - GO111MODULE=off
    args: ['get', 'github.com/mattn/goveralls']
  - name: 'gcr.io/cloud-builders/go'
    args: ['test', '-coverprofile=coverage.out', '-covermode=atomic', './...']
    env:
      - GO111MODULE=on
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: '/go/bin/goveralls'
    args: ['-coverprofile=coverage.out', '-service=travis-ci', '-covermode=atomic', '-repotoken', '${_COVERALLS_REPO_TOKEN}']
    env:
      - GO111MODULE=on
#  @ToDo: Replace with GoReleaser call.
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/openexchange-webservice-go:${BRANCH_NAME}', '.']
options:
  env:
    - GOPATH=/go
  volumes:
    - name: go-modules
      path: /go
images:
  - 'gcr.io/${PROJECT_ID}/openexchange-webservice-go:${BRANCH_NAME}'